import type { Metadata } from 'next'
import { Jost, Inter, Work_Sans } from "next/font/google";

import './globals.css'

const work_sans = Work_Sans({
	subsets: ["latin"],
	// display: 'swap',
	variable: "--font-work-sans",
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
		<html
			lang="en"
			className={`${work_sans.variable}`}
		>
			<body>{children}</body>
		</html>
  );
}
